#!/bin/bash
if [ $1 = "dirs" ]
then
  mkdir var
  mkdir var/annotations-cache
  mkdir var/output-cache
  mkdir var/template-cache
  mkdir var/tmp
  mkdir var/thumbnail
  mkdir data
  mkdir dev
  mkdir dev/dump
  mkdir data/attachment
  mkdir data/attachment-meta
  mkdir public
else
    echo 'PHLEXCLI'
    php app/index.php $*
fi
